### ISSUE TITLE
BaseParserForList<Token, int> EOF Issue

### ISSUE THREAD

**Issue by apmorton** [qwertie/Loyc#13]
Hello,

I would like to start off by saying this is a pretty impressive project, I have spent the last week or two digesting the sheer amount of code it involves. *may the odds be ever in your favor*

I am trying to use LLLPG 1.3.2, with the following parser definition (partial code, obviously)

```C#
public partial class GpcParser : BaseParserForList<Token, int>
{
    LLLPG(parser(laType(TokenType), matchType(int)));

    alias("{" = TT.LBrace);
    alias("}" = TT.RBrace);
    alias(";" = TT.Semicolon);

    private token ScanToEndOfStmt() @[
        // Used for error recovery
        (greedy(~(";"|"{")))*
        greedy(";" | "{" "}"?)?
    ];
}
```

The following code is generated for the `ScanToEndOfStmt` function

```C#
void ScanToEndOfStmt()
{
	TokenType la0;
	// Line 50: greedy(~(EOF|TT.LBrace|TT.Semicolon))*
	for (;;) {
		la0 = (TokenType) LA0;
		if (!(la0 == EOF || la0 == TT.LBrace || la0 == TT.Semicolon))
			Skip();
		else
			break;
	}
	// Line 51: greedy(TT.Semicolon | TT.LBrace (TT.RBrace)?)?
	la0 = (TokenType) LA0;
	if (la0 == TT.Semicolon)
		Skip();
	else if (la0 == TT.LBrace) {
		Skip();
		// Line 51: (TT.RBrace)?
		la0 = (TokenType) LA0;
		if (la0 == TT.RBrace)
			Skip();
	}
}
```

Which fails to compile with the following error:
```
Operator '==' cannot be applied to operands of type 'TokenType' and 'int'
```
on this segment `la0 == EOF`

`EOF` is defined as `MatchType EOF` in `BaseParser<Token, MatchType>`

Is there something I am missing regarding usage of this base class, or is this a true bug?

I am trying to read my way through the EcsParser as an example, which does not use the new base classes, and adapt it for my own language implementation.

Thanks,
Austin Morton

**Comment by qwertie** [comment]
I guess it couldn't hurt if LLLPG emitted `la0 == ($laType) EOF` (i.e. `la0 == (TokenType) EOF`) instead of just `la0 == EOF`.

`EcsParser` and `LesParser` deal with this by defining 

    new const TT EOF = TT.EOF;

**Comment by apmorton** [comment]
Perfect, I knew there must be something simple I was missing.

Thanks for pointing out the LesParser, it is indeed much easier on the eyes.
