### ISSUE TITLE
Holy crap! 

### ISSUE THREAD

**Issue by ktodyruik** [qwertie/Loyc#21]
Is this the appropriate place to say, 'holy crap! You are a genius!' And I get your comment about c# enhanced being a gimmick. There is a bigger picture. Nevertheless, any professional c# developer that tolerates c# during the day to earn a salary and then goes home and codes in something better, more expressive, and more flexible should really appreciate what you are doing. Thanks!

**Comment by qwertie** [comment]
Uh... yes?

I'm curious, how did you find out about LeMP/EC#? Where did I comment about it being a 'gimmick'? I write a lot of things :)

**Comment by ktodyruik** [comment]
LOL... Sorry to embarass you. I saw the article http://loyc.net/lemp/lemp-pattern-matching.html posted on HackerNews. I think it was on page 1. 

The gimmick statement was here, and I think you are spot on about the reason the uptake of new (and much better) languages is so slow. 

https://github.com/qwertie/Loyc/issues/12

> Enhanced C# is really a gimmick - it's not the best language I could create, and it's not intended to be. I'm developing it because I think that backward compatibility is a potential fruitful way to put more power in the hands of developers. Switching languages is a risky business maneuver, and a potentially difficult one if you already have a C# code base. I think the cost and perceived risk of switching largely explains why there is slow uptake of nice languages like D, Rust, Nemerle and even Ceylon. Languages perceived to be obscure, like Nim, Plaid, or Dyvil, don't stand a chance.

I think your ideas motivating the Loyc project are really insightful. My options in my day job to stretch the expressiveness of the language I work in are quite constrained. Lemp macros is a real solution to this issue.

**Comment by qwertie** [comment]
And thanks for your comments. So, can I count you as a confirmed user of LeMP? That would make you, like, the second one.
