### ISSUE TITLE
Custom tool error ... NullReferenceException

### ISSUE THREAD

**Issue by ktodyruik** [qwertie/Loyc#24]
I went through the installation instructions on the installation page:
http://loyc.net/lemp/install.html

Installed into VS2013.

example.out.cs was created, it only includes using statements, and there were two errors:
```
Error	2	Custom tool error: Bug: unhandled exception in parser - Object reference not set to an instance of an object. (NullReferenceException)	C:\Sketchbook\LoycTest\src\HelloWorld\example.ecs	6	1	HelloWorld
Error	1	Custom tool error: An expected condition was false: nsName.Calls(S.Assign, 2) && (aliasedType = nsName[1]) != @null	C:\Sketchbook\LoycTest\src\HelloWorld\example.ecs	6	1	HelloWorld
```

**Comment by qwertie** [comment]
What was the input code exactly? I seem to recall hitting a bug or regression in `using X = Y` statements recently.... I thought I fixed it by now.

**Comment by ktodyruik** [comment]
It's the code on the installation page. I tried to follow those
instructions exactly.

**Comment by qwertie** [comment]
Well, I'm pretty puzzled because I pushed the current binaries March 9 at 1:17pm. I am using those same binaries I pushed without any problems. I'm debugging my refactored parser right now and will update the binaries again when that's done.

**Comment by ktodyruik** [comment]
Yeah. It's often difficult to reproduce someone else's issue. If you can't
reproduce it let me know and I'll try it again. Maybe I missed something.

Kerry

**Comment by qwertie** [comment]
Could you run `LeMP.exe --editor` and see if the editor is working OK?

**Comment by ktodyruik** [comment]
Yes. It is.

**Comment by ktodyruik** [comment]
I copy-pasted the example that was int he lemp editor into Visual Studio, example.ecs and it worked.

The example that worked was 

```
using System;
using System.Collections.Generic;
using Loyc;
using Loyc.Collections;
using Loyc.Syntax;
using Loyc.Syntax.Lexing;

replace (W => Console.WriteLine);
public class Program {
	public static void Main(string[] args) {
		W("Hello, World!");
	}
}
```

What wasn't working was this, which I copied off the installation page:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows
namespace Loyc.Ecs {
   class Person {
      public Person(public readonly string Name, public int WeightLb, public int Age) {}
   }
}
```

**Comment by qwertie** [comment]
Oh I see, there's a missing semicolon after `System.Windows`.

**Comment by ktodyruik** [comment]
Thanks for catching that. Would it be possible to improve the error message?

**Comment by qwertie** [comment]
Of course! NullReferenceException is always a bug and I intend to fix it.
The problem is really just one of manpower - I don't have time to make sure
all errors are handled gracefully (but I try)

On Mon, Mar 14, 2016 at 1:35 AM, ktodyruik <notifications@github.com> wrote:

> Thanks for catching that. Would it be possible to improve the error
> message?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qwertie/Loyc/issues/24#issuecomment-196009844>.
>



-- 
- David
http://qism.blogspot.com

**Comment by qwertie** [comment]
The NullReferenceException is fixed (although current error message still makes it clear that the parser is more confused about this situation than it should be...)
