### ISSUE TITLE
Installation page a little hard to find

### ISSUE THREAD

**Issue by ktodyruik** [qwertie/Loyc#25]
Hi David,

I hope you don't mind this feedback. I was poking around the documentation to understand it better. I just realized (I think) that you were just updating the documentation. I was going to mention the sourceforge links but I think you just switched them. :)

I found the installation page, but I had to go to 
http://loyc.net/ --> Click LeMP Home Page --> Scroll to the bottom

**Comment by qwertie** [comment]
Yes, I was updating some links yesterday. Let me know of any other links you think should exist but don't.

**Comment by ktodyruik** [comment]
Hi David,

There are still some sourceforge links on this page

https://github.com/qwertie/Loyc

Did you mean them to be there?

Kerry

**Comment by qwertie** [comment]
Thanks very much for bringing this to my attention! I've fixed those links
to point to GitHub.

On Wed, Mar 16, 2016 at 3:53 AM, ktodyruik <notifications@github.com> wrote:

> Hi David,
>
> There are still some sourceforge links on this page
>
> https://github.com/qwertie/Loyc
>
> Did you mean them to be there?
>
> Kerry
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/qwertie/Loyc/issues/25#issuecomment-196995455>
>



-- 
- David
http://qism.blogspot.com
